package com.hexhaus.icarrus.dao;

import javax.swing.*;
import java.awt.*;

/**
 * User: 67726e
 * Date: 03.10.11
 * Time: 10:24
 */
public class LoggingDao {
	/**
	 * Class represents the possible types of messages generated by the application
	 * for use in logging and user messages.
	 */
	public enum Status {
		Info(TrayIcon.MessageType.INFO, JOptionPane.INFORMATION_MESSAGE),
		Warning(TrayIcon.MessageType.WARNING, JOptionPane.WARNING_MESSAGE),
		Error(TrayIcon.MessageType.ERROR, JOptionPane.ERROR_MESSAGE),
		FatalError(TrayIcon.MessageType.ERROR, JOptionPane.ERROR_MESSAGE);

		private TrayIcon.MessageType trayType;
		private int paneType;

		Status(TrayIcon.MessageType trayType, int paneType) {
			this.trayType = trayType;
			this.paneType = paneType;
		}

		public TrayIcon.MessageType toTrayType() {
			return this.trayType;
		}

		public int toPaneType() {
			return this.paneType;
		}
	}

	/**
	 * @param title
	 * @param message
	 * @param status
	 */
	public static void logToFile(String title, String message, LoggingDao.Status status) {

	}
}
